services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: leetcode-in-ts
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    tty: true
    stdin_open: true
    command: sh
